// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAheUKLtG0BfeTYqNo9uu-II77nBgsXJMM',
    appId: '1:986429987637:web:1bc68cf8e605d9b1c6ca7c',
    messagingSenderId: '986429987637',
    projectId: 'shopping364',
    authDomain: 'shopping364.firebaseapp.com',
    storageBucket: 'shopping364.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChdwIZqsEBoroqRqY9dmvNYbAgHIsLf7I',
    appId: '1:986429987637:android:b0378184ca46489dc6ca7c',
    messagingSenderId: '986429987637',
    projectId: 'shopping364',
    storageBucket: 'shopping364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnmPHWW_2Jjmfold9WJ3e83fLlwCloCAo',
    appId: '1:986429987637:ios:e01f4550acba594ec6ca7c',
    messagingSenderId: '986429987637',
    projectId: 'shopping364',
    storageBucket: 'shopping364.appspot.com',
    iosClientId: '986429987637-klbnmu8jblct9be7rpgjc0i2js7uokjf.apps.googleusercontent.com',
    iosBundleId: 'com.shopping364.app',
  );
}
